name: PUtils
description: A plugin with a few misc features.
main: org.perennial.utils.PUtils
version: 1.1-SNAPSHOT
authors:
  - WhoIsJeb
softdepend:
  - Essentials

commands:
  discord:
    description: Links to the server discord.
    usage: /<command>
    permission: putils.discord
    permission-message: You do not have permission to use this command.
  map:
    description: Links to the dynmap.
    usage: /<command>
    permission: putils.map
    permission-message: You do not have permission to use this command.
  colors:
    description: Lists the color codes.
    usage: /<command>
    permission: putils.colors
    permission-message: You do not have permission to use this command.
  stats:
    description: Lists the sender´s stats.
    usage: /<command>
    permission: putils.stats
    permission-message: You do not have permission to use this command.
  playtime:
    description: Lists the sender´s playtime.
    usage: /<command>
    permission: putils.stats
    permission-message: You do not have permission to use this command.

permissions:
  putils.*:
    description: Gives access to all PUtils commands.
    children:
      putils.discord: true
      putils.map: true
      putils.colors: true
      putils.stats: true
  putils.discord:
    description: Gives access to /discord.
  putils.map:
    description: Gives access to /map.
  putils.colors:
    description: Gives access to /colors.
  putils.stats:
    description: Gives access to /stats and /playtime.