name: Perennial-Utilities
description: A plugin with a few misc features.
main: org.perennial.utils.PerennialUtilities
version: 2.0-SNAPSHOT
authors:
  - WhoIsJeb
softdepend:
  - Essentials

commands:
  discord:
    description: Links to the server discord.
    usage: /<command>
    permission: putils.discord
    permission-message: You do not have permission to use this command.
  map:
    description: Links to the dynmap.
    usage: /<command>
    permission: putils.map
    permission-message: You do not have permission to use this command.
  colors:
    description: Lists the color codes.
    usage: /<command>
    permission: putils.colors
    permission-message: You do not have permission to use this command.
  stats:
    description: Lists the sender´s stats.
    usage: /<command>
    permission: putils.stats
    permission-message: You do not have permission to use this command.
    aliases: [st]
  playtime:
    description: Lists the sender´s playtime.
    usage: /<command> <player>
    permission: putils.stats
    permission-message: You do not have permission to use this command.
    aliases: [pti]
  balance:
    description: Prints the sender's balance.
    usage: /<command>
    permission: putils.balance
    aliases: [bal, pbalance, pbal]
  pay:
    description: Pays the specified player the specified amount of money.
    usage: /<command> <player> <amount>
    permission: putils.pay
    aliases: [ppay]
  seen:
    description: Lists the last time specified player was online. (yyyy-MM-dd HH:mm UTC)
    usage: /<command> <player>
    permission: putils.seen
    permission-message: You do not have permission to use this command.
  putils:
    description: Lists the version/author, or a list of the commands.
    usage: /<command>
    aliases: [pu]
  joinmsg:
    description: Allows one to set their own custom join message.
    usage: /<command>
    permission: putils.custom-joinmsg
    permission-message: You do not have permission to use this command.
    aliases: [jmsg]
  quitmsg:
    description: Allows one to set their own custom quit message.
    usage: /<command>
    permission: putils.custom-quitmsg
    permission-message: You do not have permission to use this command.
    aliases: [qmsg]
  register:
    description: Registers new players.
    usage: /<command> <password>
    aliases: [ pregister, reg, preg ]
  login:
    description: Logs one in.
    usage: /<command> <password>
    aliases: [ plogin, li, pli ]

permissions:
  putils.*:
    description: Gives access to all PerennialUtilities commands.
    children:
      putils.discord: true
      putils.map: true
      putils.colors: true
      putils.stats: true
      putils.seen: true
      putils.fakeop: true
      putils.debug: true
  putils.discord:
    description: Gives access to /discord.
  putils.map:
    description: Gives access to /map.
  putils.colors:
    description: Gives access to /colors.
  putils.stats:
    description: Gives access to /stats and /playtime.
  putils.balance:
    description: Gives access to /bal and /baltop.
  putils.pay:
    description: Gives access to /pay.
  putils.seen:
    description: Gives access to /seen.
  putils.debug:
    description: Gives access to more subcommands of /putils.
  putils.custom-joinmsg:
    description: Gives access to /joinmsg <set|clear>
  putils.custom-quitmsg:
    description: Gives access to /quitmsg <set|clear|view|?>